# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install
      - run: npm i -g snyk
      - run: snyk auth ${{ secrets.SNYK_TOKEN }}
      - name: Installing snyk-delta and dependencies
        run: npm i -g snyk-delta
      - uses: snyk/actions/setup@master
      - run: snyk test --json | jq 'del(.vulnerabilities[]? | select(.severity=="low" or .severity=="medium" or .severity=="high"))' | snyk-delta --setPassIfNoBaseline="true" 

      

     # - name: install snyk-to-html
     #   run: |
         # npm install snyk-to-html -g
         # mkdir downloads
         # cp -v /home/runner/work/nodejs-goof/nodejs-goof/*.html /home/runner/work/nodejs-goof/nodejs-goof/downloads
    #  - name: Use the Upload Artifact GitHub Action
    #   uses: actions/upload-artifact@v2
    #    with:
    #     name: results
    #   path: downloads
